title: Hunter's Security Blog
author:
  name: Hunter Mason
description: > # this means to ignore newlines until "show_excerpts:"
  Tips and Tricks about Application and Product Security. 
  Web Application and API Penetration Testing, Secure Code Reviews, and more
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    twitter: HuntMSecurity
    github:  HMason34
    linkedin: hunter-mason

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
